/* Automatic generated by './build/bin/build-entry.js' */

import ElxOption from '../packages/elx-option/index.js';
import ElxPlaceholder from '../packages/elx-placeholder/index.js';
import ElxOperateParam from '../packages/elx-operate-param/index.js';
import ElxParamForm from '../packages/elx-param-form/index.js';
import ElxCardList from '../packages/elx-card-list/index.js';
import ElxMenu from '../packages/elx-menu/index.js';
import ElxSelect from '../packages/elx-select/index.js';
import ElxDatePickerGroup from '../packages/elx-date-picker-group/index.js';
import ElxMain from '../packages/elx-main/index.js';
import ElxBreadcrumb from '../packages/elx-breadcrumb/index.js';
import ElxTableColumn from '../packages/elx-table-column/index.js';
import ElxOperateButton from '../packages/elx-operate-button/index.js';
import ElxOperateItem from '../packages/elx-operate-item/index.js';
import ElxOperateExpandItem from '../packages/elx-operate-expand-item/index.js';
import ElxTable from '../packages/elx-table/index.js';
import ElxSidebar from '../packages/elx-sidebar/index.js';
import ElxNavbar from '../packages/elx-navbar/index.js';
import ElxContent from '../packages/elx-content/index.js';
import ElxForm from '../packages/elx-form/index.js';
import ElxTabFrame from '../packages/elx-tab-frame/index.js';
import ElxTabs from '../packages/elx-tabs/index.js';
import ElxSidebarP from '../packages/elx-sidebar-p/index.js';
import ElxTree from '../packages/elx-tree/index.js';
import ElxItemList from '../packages/elx-item-list/index.js';
import ElxFilter from '../packages/elx-filter/index.js';
import ElxFilterItem from '../packages/elx-filter-item/index.js';
import ElxMenuExpand from '../packages/elx-menu-expand/index.js';
import ElxCascader from '../packages/elx-cascader/index.js';
import ElxRadio from '../packages/elx-radio/index.js';
import ElxRadioGroup from '../packages/elx-radio-group/index.js';
import ElxTableForm from '../packages/elx-table-form/index.js';
import ElxCardForm from '../packages/elx-card-form/index.js';
import ElxFormGroup from '../packages/elx-form-group/index.js';
import ElxContextMenu from '../packages/elx-context-menu/index.js';
import ElxCodemirror from '../packages/elx-codemirror/index.js';
import ElxAside from '../packages/elx-aside/index.js';
import ElxHeader from '../packages/elx-header/index.js';
import ElxScrollContent from '../packages/elx-scroll-content/index.js';
import ElxFooter from '../packages/elx-footer/index.js';
import ElxCheckbox from '../packages/elx-checkbox/index.js';
import ElxCheckboxGroup from '../packages/elx-checkbox-group/index.js';
import ElxCron from '../packages/elx-cron/index.js';
import ElxRemoteTransfer from '../packages/elx-remote-transfer/index.js';
import ElxNavbarConsole from '../packages/elx-navbar-console/index.js';
import ElxInputTransfer from '../packages/elx-input-transfer/index.js';
import ElxRowResizeLayout from '../packages/elx-row-resize-layout/index.js';
import ElxColResizeLayout from '../packages/elx-col-resize-layout/index.js';
import ElxElTree from '../packages/elx-el-tree/index.js';
import ElxSelectInput from '../packages/elx-select-input/index.js';
import ElxTopMenu from '../packages/elx-top-menu/index.js';
import Contextmenu from '../packages/contextmenu/index.js';
import locale from 'element-uex/src/locale';

const components = [
  ElxOption,
  ElxPlaceholder,
  ElxOperateParam,
  ElxParamForm,
  ElxCardList,
  ElxMenu,
  ElxSelect,
  ElxDatePickerGroup,
  ElxMain,
  ElxBreadcrumb,
  ElxTableColumn,
  ElxOperateButton,
  ElxOperateItem,
  ElxOperateExpandItem,
  ElxTable,
  ElxSidebar,
  ElxNavbar,
  ElxContent,
  ElxForm,
  ElxTabFrame,
  ElxTabs,
  ElxSidebarP,
  ElxTree,
  ElxItemList,
  ElxFilter,
  ElxFilterItem,
  ElxMenuExpand,
  ElxCascader,
  ElxRadio,
  ElxRadioGroup,
  ElxTableForm,
  ElxCardForm,
  ElxFormGroup,
  ElxContextMenu,
  ElxCodemirror,
  ElxAside,
  ElxHeader,
  ElxScrollContent,
  ElxFooter,
  ElxCheckbox,
  ElxCheckboxGroup,
  ElxCron,
  ElxRemoteTransfer,
  ElxNavbarConsole,
  ElxInputTransfer,
  ElxRowResizeLayout,
  ElxColResizeLayout,
  ElxElTree,
  ElxSelectInput,
  ElxTopMenu
];

const install = function(Vue, opts = {}) {
  /* istanbul ignore if */
  if (install.installed) return;
  locale.use(opts.locale);
  locale.i18n(opts.i18n);

  components.map(component => {
    Vue.component(component.name, component);
  });
  Vue.use(Contextmenu.directive);

  Vue.prototype.$ELEMENTUEX = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  };
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
};

export default {
  version: '2.0.2',
  locale: locale.use,
  i18n: locale.i18n,
  install,
  Contextmenu,
  ElxOption,
  ElxPlaceholder,
  ElxOperateParam,
  ElxParamForm,
  ElxCardList,
  ElxMenu,
  ElxSelect,
  ElxDatePickerGroup,
  ElxMain,
  ElxBreadcrumb,
  ElxTableColumn,
  ElxOperateButton,
  ElxOperateItem,
  ElxOperateExpandItem,
  ElxTable,
  ElxSidebar,
  ElxNavbar,
  ElxContent,
  ElxForm,
  ElxTabFrame,
  ElxTabs,
  ElxSidebarP,
  ElxTree,
  ElxItemList,
  ElxFilter,
  ElxFilterItem,
  ElxMenuExpand,
  ElxCascader,
  ElxRadio,
  ElxRadioGroup,
  ElxTableForm,
  ElxCardForm,
  ElxFormGroup,
  ElxContextMenu,
  ElxCodemirror,
  ElxAside,
  ElxHeader,
  ElxScrollContent,
  ElxFooter,
  ElxCheckbox,
  ElxCheckboxGroup,
  ElxCron,
  ElxRemoteTransfer,
  ElxNavbarConsole,
  ElxInputTransfer,
  ElxRowResizeLayout,
  ElxColResizeLayout,
  ElxElTree,
  ElxSelectInput,
  ElxTopMenu
};
